import {
    CDB_SPLIT_LOG_MAX_BYTES,
    CDB_SPLIT_LOG_MAX_ROWS,
    CDB_SPLIT_TX_MAX_BYTES,
    CDB_SPLIT_TX_MAX_ROWS,
    CDB_SPLIT_TX_MAX_ROW_BYTES,
} from "../oplog/schema.ts";

export type CdbSystemTailKind = "file" | "vector";

export interface CdbSystemTailAppend {
    readonly migId: string;
    readonly kind: CdbSystemTailKind;
    readonly table: string;
    readonly op: "ins" | "upd" | "del";
    readonly pkSql: string;
    readonly placementSql: string;
    readonly beforeSql: string;
    readonly afterSql: string;
    readonly assertionsSql?: string;
}

export function cdbSystemTailMigrationId(value: string): string {
    if (!/^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(value)) {
        throw new Error("system reshard migration id is invalid");
    }
    return value;
}

export function cdbSystemTailTriggerId(value: string): string {
    const id = cdbSystemTailMigrationId(value);
    let encoded = "m_";
    for (let index = 0; index < id.length; index++) {
        encoded += id.charCodeAt(index).toString(16).padStart(2, "0");
    }
    return encoded;
}

/** Trigger suffix used before migration IDs received an injective encoding. */
export function cdbLegacySystemTailTriggerId(value: string): string {
    return cdbSystemTailMigrationId(value).replaceAll("-", "_");
}

/**
 * Render the common, bounded append used by side-state capture triggers.
 * Every SQL expression passed here is generated by a resource-specific module,
 * never from an RPC argument.
 */
export function renderCdbSystemTailAppend(input: CdbSystemTailAppend): string {
    const migId = cdbSystemTailMigrationId(input.migId);
    if (!/^_chardb_[a-z0-9_]+$/.test(input.table)) throw new Error("system reshard table name is invalid");
    const pendingId =
        "(SELECT event_id FROM _chardb_op_log WHERE byte_size = 0 AND length(payload_enc) = 0 ORDER BY event_id LIMIT 1)";
    const pendingCount =
        "(SELECT COUNT(*) FROM (SELECT 1 FROM _chardb_op_log WHERE byte_size = 0 AND length(payload_enc) = 0 LIMIT 2))";
    const pendingPlacement =
        "(SELECT placement_vshard FROM _chardb_op_log WHERE byte_size = 0 AND length(payload_enc) = 0 ORDER BY event_id LIMIT 1)";
    const externalId = "(SELECT active_id FROM _chardb_split_capture_tx WHERE singleton = 1)";
    const externalPlacement = "(SELECT active_vshard FROM _chardb_split_capture_tx WHERE singleton = 1)";
    const transactionId = `COALESCE(${pendingId}, ${externalId})`;
    const active = [
        "EXISTS (SELECT 1 FROM _chardb_split_state AS state ",
        `WHERE state.mig_id = '${migId}' AND state.role = 'source' AND state.capture = 1 `,
        `AND (${input.placementSql}) BETWEEN state.range_lo AND state.range_hi)`,
    ].join("");
    const accountedBytes =
        `32 + length(CAST('${migId}' AS BLOB)) + length(CAST('${input.op}' AS BLOB)) + ` +
        `length(CAST('${input.table}' AS BLOB)) + length(CAST(json_quote(CAST(${input.pkSql} AS TEXT) || '') AS BLOB)) + ` +
        `length(CAST(COALESCE(${input.beforeSql}, '') AS BLOB)) + ` +
        `length(CAST(COALESCE(${input.afterSql}, '') AS BLOB))`;
    const transferBytes =
        `256 + 2 * (length(CAST('${input.op}' AS BLOB)) + length(CAST('${input.table}' AS BLOB)) + ` +
        `length(CAST(json_quote(CAST(${input.pkSql} AS TEXT) || '') AS BLOB)) + ` +
        `length(CAST(COALESCE(${input.beforeSql}, '') AS BLOB)) + ` +
        `length(CAST(COALESCE(${input.afterSql}, '') AS BLOB)))`;
    return [
        input.assertionsSql ?? "",
        `SELECT CASE WHEN (${active}) AND (SELECT COUNT(*) FROM _chardb_split_state `,
        `WHERE role = 'source' AND capture = 1 AND (${input.placementSql}) BETWEEN range_lo AND range_hi) != 1 `,
        `THEN RAISE(ABORT, 'CDB_INVARIANT: overlapping active ${input.kind} splits') END; `,
        `SELECT CASE WHEN (${active}) AND ((${pendingCount}) + ((${externalId}) IS NOT NULL)) != 1 `,
        `THEN RAISE(ABORT, 'CDB_INVARIANT: ${input.kind} capture requires exactly one transaction identity') END; `,
        `SELECT CASE WHEN (${active}) AND ${pendingId} IS NOT NULL AND ${pendingPlacement} IS NOT (${input.placementSql}) `,
        `THEN RAISE(ABORT, 'CDB_INVARIANT: mutation and ${input.kind} placement differ') END; `,
        `SELECT CASE WHEN (${active}) AND ${externalId} IS NOT NULL AND ${externalPlacement} IS NOT (${input.placementSql}) `,
        `THEN RAISE(ABORT, 'CDB_INVARIANT: external ${input.kind} transaction placement differs') END; `,
        "UPDATE _chardb_split_state SET split_log_rows = split_log_rows + 1, ",
        `split_log_bytes = split_log_bytes + (${accountedBytes}), `,
        `capture_tx_rows = CASE WHEN capture_tx_id IS ${transactionId} THEN capture_tx_rows + 1 ELSE 1 END, `,
        `capture_tx_bytes = CASE WHEN capture_tx_id IS ${transactionId} `,
        `THEN capture_tx_bytes + (${transferBytes}) ELSE (${transferBytes}) END, `,
        `capture_tx_id = ${transactionId} `,
        `WHERE mig_id = '${migId}' AND role = 'source' AND capture = 1 `,
        `AND (${input.placementSql}) BETWEEN range_lo AND range_hi `,
        `AND split_log_rows < ${CDB_SPLIT_LOG_MAX_ROWS} `,
        `AND split_log_bytes <= ${CDB_SPLIT_LOG_MAX_BYTES} - (${accountedBytes}) `,
        `AND (${transferBytes}) <= ${CDB_SPLIT_TX_MAX_ROW_BYTES} `,
        `AND (${transferBytes}) <= ${CDB_SPLIT_TX_MAX_BYTES} `,
        `AND (capture_tx_id IS NOT ${transactionId} OR capture_tx_rows < ${CDB_SPLIT_TX_MAX_ROWS}) `,
        `AND (capture_tx_id IS NOT ${transactionId} `,
        `OR capture_tx_bytes <= ${CDB_SPLIT_TX_MAX_BYTES} - (${transferBytes})); `,
        `SELECT CASE WHEN (${active}) AND changes() != 1 `,
        "THEN RAISE(ABORT, 'CDB_RATE_LIMITED: source split log capacity reached') END; ",
        "INSERT INTO _chardb_split_log (source_tx_id, mig_id, op, table_name, pk, before, after, ts) ",
        `SELECT ${transactionId}, '${migId}', '${input.op}', '${input.table}', CAST(${input.pkSql} AS TEXT), `,
        `${input.beforeSql}, ${input.afterSql}, CAST(strftime('%s','now') AS INTEGER) * 1000 WHERE (${active});`,
    ].join("");
}
