import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
    entries: [
        "src/index",
        "src/server/index",
        "src/react/index",
        "src/files/index",
        "src/internal/vector-proof",
        { input: "src/cli/bin", name: "cli/bin" },
        { input: "src/cli/schema-inspector-preload", name: "cli/schema-inspector-preload" },
        "src/vite/index",
    ],
    declaration: "compatible",
    clean: true,
    rollup: {
        emitCJS: false,
        inlineDependencies: false,
        esbuild: { target: "es2022" },
    },
    externals: [
        "drizzle-orm",
        "better-auth",
        "@better-auth/core",
        "@standard-schema/spec",
        "hono",
        "react",
        "react-dom",
        "bun",
        "cloudflare:workers",
        "node:crypto",
        "node:buffer",
        "vite",
        "@cloudflare/vite-plugin",
        "miniflare",
        "eslint",
        "@typescript-eslint/utils",
    ],
    failOnWarn: true,
});
