import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
    entries: [
        "src/index",
        "src/server/index",
        "src/drizzle/index",
        "src/files/index",
        "src/files/validators/zod",
        "src/files/validators/typebox",
        "src/files/validators/valibot",
        "src/files/validators/arktype",
        "src/auth/index",
        "src/react/index",
        "src/cli/index",
        { input: "src/cli/bin", name: "cli/bin" },
        "src/vite/index",
        "src/miniflare-plugin/index",
        "src/observability/index",
        "src/reshard/index",
        "src/eslint-plugin/index",
    ],
    declaration: "compatible",
    clean: true,
    rollup: {
        emitCJS: false,
        inlineDependencies: false,
        esbuild: { target: "es2022" },
    },
    externals: [
        "drizzle-orm",
        "better-auth",
        "@better-auth/core",
        "@standard-schema/spec",
        "hono",
        "react",
        "react-dom",
        "cloudflare:workers",
        "node:crypto",
        "node:buffer",
        "vite",
        "@cloudflare/vite-plugin",
        "miniflare",
        "eslint",
        "@typescript-eslint/utils",
    ],
    failOnWarn: false,
});
