import type { ChardbMigrationInput } from "../server/schema-migrations.ts";
import type { ChardbSchemaSnapshotInput } from "../server/schema-snapshot.ts";
import { stableJson } from "../util/canonical.ts";

export interface InitialMigrationArtifacts {
    readonly versionOne: string;
    readonly snapshotOne: string;
    readonly journal: string;
}

export interface AdditiveMigrationArtifacts {
    readonly versionFile: string;
    readonly snapshotFile: string;
    readonly journal: string;
}

function migrationBinding(version: number): string {
    return `migrationV${version}`;
}

function renderJournal(versions: readonly number[]): string {
    const imports = versions
        .map(version =>
            version === 1
                ? 'import { initialSchema } from "./migrations/v1.ts";'
                : `import { migration as ${migrationBinding(version)} } from "./migrations/v${version}.ts";`
        )
        .join("\n");
    const entries = versions.map(version => (version === 1 ? "initialSchema" : migrationBinding(version)));
    return `import { defineMigrations } from "@chardb/core/server";
${imports}

export const migrations = defineMigrations([
${entries.map(entry => `  ${entry},`).join("\n")}
]);
`;
}

/** Render static source files. The emitted history never imports mutable schema or auth modules. */
export function renderInitialMigrationArtifacts(snapshot: ChardbSchemaSnapshotInput): InitialMigrationArtifacts {
    const literal = JSON.stringify(snapshot, null, 2);
    const versionOne = `import { defineSchemaSnapshot } from "@chardb/core/server";

// Generated immutable version-one schema snapshot. Do not edit this file after
// a deployment reaches version 1.
export const initialSchema = defineSchemaSnapshot(${literal} as const).initialMigration;
`;
    return Object.freeze({ versionOne, snapshotOne: `${stableJson(snapshot)}\n`, journal: renderJournal([1]) });
}

/** Render one append-only snapshot and migration plus the complete static journal. */
export function renderAdditiveMigrationArtifacts(
    snapshot: ChardbSchemaSnapshotInput,
    migration: ChardbMigrationInput
): AdditiveMigrationArtifacts {
    if (snapshot.version !== migration.version || snapshot.version < 2) {
        throw new Error("additive migration artifact version mismatch");
    }
    const snapshotLiteral = JSON.stringify(snapshot, null, 2);
    const migrationLiteral = JSON.stringify(migration, null, 2);
    const versionFile = `import { defineSchemaSnapshot } from "@chardb/core/server";

// Generated immutable version-${snapshot.version} schema snapshot and reviewed
// additive migration. Do not edit this file after deployment.
export const schemaSnapshot = defineSchemaSnapshot(${snapshotLiteral} as const);

export const migration = Object.freeze(${migrationLiteral} as const);
`;
    return Object.freeze({
        versionFile,
        snapshotFile: `${stableJson(snapshot)}\n`,
        journal: renderJournal(Array.from({ length: snapshot.version }, (_, index) => index + 1)),
    });
}
