import type { CliContext } from "../context.ts";
import { renderWrangler } from "../wrangler_template.ts";

export interface InitOptions {
    readonly name: string;
    readonly compatibilityDate?: string;
}

const DEFAULT_COMPAT_DATE = "2026-05-10";

const PACKAGE_TEMPLATE = (name: string) =>
    `${JSON.stringify(
        {
            name,
            private: true,
            version: "0.0.0",
            type: "module",
            packageManager: "bun@1.2.22",
            scripts: {
                typecheck: "tsc --noEmit",
                build: "wrangler deploy --dry-run --outdir dist",
                dev: "wrangler dev",
            },
            dependencies: {
                "better-auth": "1.6.30",
                chardb: "0.1.0",
                "drizzle-orm": "0.45.2",
                zod: "4.4.3",
            },
            devDependencies: {
                "@cloudflare/workers-types": "4.20260510.1",
                typescript: "5.9.3",
                wrangler: "4.125.0",
            },
        },
        null,
        2
    )}\n`;

const TSCONFIG_TEMPLATE = `${JSON.stringify(
    {
        compilerOptions: {
            lib: ["ES2023"],
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "Bundler",
            moduleDetection: "force",
            allowImportingTsExtensions: true,
            verbatimModuleSyntax: true,
            noEmit: true,
            strict: true,
            exactOptionalPropertyTypes: true,
            noUncheckedIndexedAccess: true,
            skipLibCheck: true,
            isolatedModules: true,
            types: ["@cloudflare/workers-types"],
        },
        include: ["src/**/*.ts"],
        exclude: ["node_modules", "dist"],
    },
    null,
    2
)}\n`;

const GITIGNORE_TEMPLATE = `node_modules/
dist/
.dev.vars
.wrangler/
worker-configuration.d.ts
`;

const DASHBOARD_TEMPLATE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>chardb dashboard</title>
  </head>
  <body>
    <p>The chardb dashboard is not included in this prototype.</p>
  </body>
</html>
`;

const README_TEMPLATE = (name: string) => `# ${name}

This project was generated by \`chardb init\`.

\`bun install\` installs its pinned dependencies. \`bun run typecheck\` checks the Worker, and \`bun run build\` asks Wrangler to validate and bundle it without deploying.

The current chardb prototype does not apply domain migrations or provide a complete authenticated mutation, initial-query, and live-update path. Do not deploy this scaffold with production data.
`;

const SCHEMA_TEMPLATE = `import { integer, text } from "drizzle-orm/sqlite-core";
import { forOrg } from "chardb/server";
import { auth } from "./worker.ts";

const { cdbTable } = forOrg();

export const messages = cdbTable(
  "messages",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id")
      .notNull()
      .references(() => auth.organization.id, { onDelete: "cascade" }),
    authorId: text("author_id")
      .notNull()
      .references(() => auth.user.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  {
    selfBy: "authorId",
    roles: {
      admin: "*",
      member: { read: "*", create: ["id", "body", "createdAt"] },
      self: { read: "*", update: ["body"], delete: true },
    },
  },
);
`;

const API_TEMPLATE = `import { api } from "chardb/server";
import { z } from "zod";
import { messages } from "./schema.ts";

export const postMessage = api.mutation({
  ref: "src/api.ts#postMessage",
  authority: "organization",
  args: z.object({
    id: z.string(),
    organizationId: z.string(),
    body: z.string().min(1),
    clientCreatedAt: z.number(),
  }),
  partitionKey: "organizationId",
  handler: (ctx, args) => {
    if (!ctx.auth.userId || !ctx.auth.tenantId || ctx.auth.tenantId !== args.organizationId) {
      throw new Error("CDB_FORBIDDEN: active organization does not match the routed partition");
    }
    ctx.db.insert(messages).values({
      id: args.id,
      body: args.body,
      createdAt: args.clientCreatedAt,
    }).run();
    return { id: args.id };
  },
});
`;

const WORKER_TEMPLATE = `import { anonymous } from "better-auth/plugins/anonymous";
import { jwt } from "better-auth/plugins/jwt";
import { chardb, defineAuth } from "chardb/server";
import * as api from "./api.ts";
import * as domain from "./schema.ts";

// Better-auth profile. Plugin tables are inferred from the tuple;
// \`auth.user\`, \`auth.organization\`, etc. are typed Drizzle tables
// the domain schema FKs into. Declared at the top level so
// \`schema.ts\` can \`import { auth } from "./worker.ts"\` cleanly.
export const auth = defineAuth({
  appName: {{APP_NAME}},
  plugins: [anonymous(), jwt()],
});

// One factory call composes the runtime: merged Drizzle schema, lazy
// manifest from \`api\`'s exports, Hono router for non-reserved routes,
// the six Durable Object classes wrangler binds. The returned \`app\`
// is the wrangler-ready module — chain user routes on it directly.
export const app = chardb({ auth, schema: domain, api });

app.get("/health", (c) => c.text("ok"));

export default app;
export const { BlobMeta, Catalog, Cdb, Gateway, GsiShard, Resharder } = app;
`;

export async function runInit(ctx: CliContext, opts: InitOptions): Promise<void> {
    const compat = opts.compatibilityDate ?? DEFAULT_COMPAT_DATE;
    const wrangler = renderWrangler({
        name: opts.name,
        compatibilityDate: compat,
        assetsDir: "public",
    });
    await ctx.write(`${ctx.cwd}/package.json`, PACKAGE_TEMPLATE(opts.name));
    await ctx.write(`${ctx.cwd}/tsconfig.json`, TSCONFIG_TEMPLATE);
    await ctx.write(`${ctx.cwd}/.gitignore`, GITIGNORE_TEMPLATE);
    await ctx.write(`${ctx.cwd}/README.md`, README_TEMPLATE(opts.name));
    await ctx.write(`${ctx.cwd}/wrangler.jsonc`, `${wrangler}\n`);
    await ctx.write(`${ctx.cwd}/src/schema.ts`, SCHEMA_TEMPLATE);
    await ctx.write(`${ctx.cwd}/src/api.ts`, API_TEMPLATE);
    await ctx.write(`${ctx.cwd}/src/worker.ts`, WORKER_TEMPLATE.replace("{{APP_NAME}}", JSON.stringify(opts.name)));
    await ctx.write(`${ctx.cwd}/public/index.html`, DASHBOARD_TEMPLATE);
    ctx.stdout(`chardb: initialised "${opts.name}" with compat date ${compat}\n`);
}
